MeoAndWoofClient/Controllers/AdminController.cs
using BusinessObject.Models.DTO;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Net.Http.Headers;

namespace MeoAndWoofClient.Controllers
{
	public class AdminController : Controller
	{
		private readonly HttpClient _httpClient;

		public AdminController(HttpClient httpClient)
		{
			_httpClient = httpClient;
			_httpClient.BaseAddress = new Uri("https://localhost:7086/api/");
			_httpClient.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
			//localhost:7086/api/service/filter?userId=2&serviceTypeId=2
		}
		private IActionResult Filter()
		{
			string? admin = HttpContext.Session.GetString("IsAdmin");
			if (admin != "true") return RedirectToAction("Login", "Authen");

			return null;
		}

		public IActionResult Chart()
		{
			return View();
		}
		public IActionResult Chat()
		{
			return View();
		}
		public async Task<IActionResult> CuaHangThuCung()
		{
			IActionResult filterResult = Filter();
			if (filterResult != null) return filterResult;

			int serviceTypeId = 1;

			HttpResponseMessage response = await _httpClient.GetAsync($"service?$filter=serviceTypeId eq {serviceTypeId}");

			if (response.IsSuccessStatusCode)
			{
				string content = await response.Content.ReadAsStringAsync();
				List<ServiceDTO> services = JsonConvert.DeserializeObject<List<ServiceDTO>>(content);
				HttpContext.Session.SetInt32("ServiceId", services.FirstOrDefault()?.Serviceid ?? 0);
				return View(services);
			}

			return View(new List<ServiceDTO>());
		}
		public async Task<IActionResult> LuuTruThuCung()
		{
			IActionResult filterResult = Filter();
			if (filterResult != null) return filterResult;

			int serviceTypeId = 2;

			HttpResponseMessage response = await _httpClient.GetAsync($"service?$filter=serviceTypeId eq {serviceTypeId}");

			if (response.IsSuccessStatusCode)
			{
				string content = await response.Content.ReadAsStringAsync();
				List<ServiceDTO> services = JsonConvert.DeserializeObject<List<ServiceDTO>>(content);
				HttpContext.Session.SetInt32("ServiceId", services.FirstOrDefault()?.Serviceid ?? 0);
				return View(services);
			}

			return View(new List<ServiceDTO>());
		}
		public IActionResult Dashboard()
		{
			return View();
		}
		public IActionResult StoreProduct()
		{
			return View();
		}
	}
}

MeoAndWoofClient/Controllers/UserController.cs
using BusinessObject.Models;
using BusinessObject.Models.DTO;
using BusinessObject.ObjectView;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Net;
namespace MeoAndWoofClient.Controllers
{
    public class UserController : Controller
    {
        private readonly HttpClient _httpClient;
        private readonly IConfiguration _configuration;
        private readonly IWebHostEnvironment _hostEnvironment;

        public UserController(IConfiguration configuration, IWebHostEnvironment hostEnvironment)
        {
            _httpClient = new HttpClient
            {
                BaseAddress = new Uri("https://localhost:7086/api/")
            };
            _configuration = configuration;
            _hostEnvironment = hostEnvironment;
        }
        private int? GetUserId() => HttpContext.Session.GetInt32("UserId");
        public async Task<IActionResult> ChangePass(int id)
        {
            HttpResponseMessage userResponse = await _httpClient.GetAsync($"user/{id}");
            User user = new();
            if (userResponse.StatusCode == HttpStatusCode.OK)
            {
                string userContent = await userResponse.Content.ReadAsStringAsync();
                user = JsonConvert.DeserializeObject<User>(userContent);
            }

            return View(user);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ChangePass(User user, int id, [FromForm] string OldPassword, [FromForm] string Password, [FromForm] string RePassword)
        {
            ModelState.Remove("Sdt");
            ModelState.Remove("Username");
            ModelState.Remove("Fullname");
            ModelState.Remove("Address");
            ModelState.Remove("Email");
            ModelState.Remove("Role");
            HttpResponseMessage userResponse = await _httpClient.GetAsync($"user/{id}/getpass");
            User userDTO = new();
            if (userResponse.StatusCode == HttpStatusCode.OK)
            {
                string userContent = await userResponse.Content.ReadAsStringAsync();
                userDTO = JsonConvert.DeserializeObject<User>(userContent);
                if (userDTO.Password != OldPassword)
                {
                    ModelState.AddModelError(string.Empty, "Mật khẩu hiện tại không chính xác");
                    return View(userDTO);
                }
                ViewBag.OldPassword = OldPassword;
                if (ModelState.IsValid)
                {
                    if (Password != RePassword)
                    {
                        ModelState.AddModelError(string.Empty, "Mật khẩu không khớp");
                        return View(userDTO);
                    }
                    userDTO.Password = Password;
                    userDTO.Userid = id;
                    HttpResponseMessage changePassResponse = await _httpClient.PutAsJsonAsync($"user/{id}/changepass", userDTO);
                    if (changePassResponse.StatusCode == HttpStatusCode.OK)
                    {
                        ModelState.Clear();
                        return Ok("User information updated successfully.");
                    }
                    else
                    {
                        return StatusCode((int)changePassResponse.StatusCode, $"Failed to update user. Status code: {changePassResponse.StatusCode}");
                    }
                }
            }

            return View(userDTO);
        }

        public async Task<IActionResult> HistoryBooking(int id)
        {
            HttpResponseMessage userResponse = await _httpClient.GetAsync($"booking?$filter=userid eq {id}");
            List<BookingDTO> bookingDTOs = new();
            if (userResponse.StatusCode == HttpStatusCode.OK)
            {
                string userContent = await userResponse.Content.ReadAsStringAsync();
                bookingDTOs = JsonConvert.DeserializeObject<List<BookingDTO>>(userContent);
            }

            return View(bookingDTOs);
        }
        public async Task<IActionResult> HistoryStore(int id)
        {
            HttpResponseMessage userResponse = await _httpClient.GetAsync($"order?$filter=userid eq {id}");
            List<OrderDTO> orderDTOs = new();
            if (userResponse.StatusCode == HttpStatusCode.OK)
            {
                string userContent = await userResponse.Content.ReadAsStringAsync();
                orderDTOs = JsonConvert.DeserializeObject<List<OrderDTO>>(userContent);
            }
            orderDTOs = orderDTOs.OrderByDescending(o => o.OrderId).ToList();
            return View(orderDTOs);
        }
        public async Task<IActionResult> Information(int id)
        {
            HttpResponseMessage userResponse = await _httpClient.GetAsync($"user/{id}");
            HttpResponseMessage petsResponse = await _httpClient.GetAsync($"pet?$filter=userid eq {id}");
            MyInforView view = new();
            if (userResponse.StatusCode == HttpStatusCode.OK)
            {
                string userContent = await userResponse.Content.ReadAsStringAsync();
                UserDTO userDTO = JsonConvert.DeserializeObject<UserDTO>(userContent);
                view.userDTO = userDTO;
            }
            if (petsResponse.StatusCode == HttpStatusCode.OK)
            {
                string petContent = await petsResponse.Content.ReadAsStringAsync();
                List<PetDTO> PetDTOs = JsonConvert.DeserializeObject<List<PetDTO>>(petContent);
                view.petDTOs = PetDTOs;
            }

            return View(view);
        }

        [HttpPost]
        public async Task<IActionResult> Information(UserDTO userDTO, int id, IFormFile Userimage, string OldUserImage)
        {
            userDTO.Userid = id;

            if (Userimage != null && Userimage.Length > 0)
            {
                try
                {
                    string uploadsFolder = Path.Combine(_hostEnvironment.WebRootPath, "img", "avatar");
                    string uniqueFileName = Guid.NewGuid().ToString() + "_" + Userimage.FileName;
                    string filePath = Path.Combine(uploadsFolder, uniqueFileName);

                    if (!string.IsNullOrEmpty(OldUserImage))
                    {
                        string oldFilePath = Path.Combine(_hostEnvironment.WebRootPath, OldUserImage.TrimStart('/'));
                        if (System.IO.File.Exists(oldFilePath))
                        {
                            System.IO.File.Delete(oldFilePath);
                        }
                    }

                    using (FileStream fileStream = new(filePath, FileMode.Create))
                    {
                        await Userimage.CopyToAsync(fileStream);
                    }
                    userDTO.Userimage = "/img/avatar/" + uniqueFileName;
                }
                catch (Exception ex)
                {
                    return StatusCode(500, $"Internal server error: {ex.Message}");
                }

            }
            HttpResponseMessage userResponse = await _httpClient.PutAsJsonAsync($"user/{id}", userDTO);

            if (userResponse.StatusCode == HttpStatusCode.OK || userResponse.StatusCode == HttpStatusCode.NoContent)
            {
                HttpContext.Session.SetString("CompleteProfile", "false");
                return RedirectToAction("Index", "Home");
            }
            else
            {
                ModelState.AddModelError(string.Empty, $"Failed to update user. Status code: {userResponse.StatusCode}");
                return View(userDTO);
            }
        }
        public async Task<IActionResult> EditPet(int id)
        {
            HttpResponseMessage response = await _httpClient.GetAsync($"pet/{id}");
            if (response.StatusCode == HttpStatusCode.OK)
            {
                string petContent = await response.Content.ReadAsStringAsync();
                PetDTO petDTO = JsonConvert.DeserializeObject<PetDTO>(petContent);

                HttpResponseMessage petTypesResponse = await _httpClient.GetAsync("pettype");
                if (petTypesResponse.IsSuccessStatusCode)
                {
                    string petTypesData = await petTypesResponse.Content.ReadAsStringAsync();
                    List<PetTypeDTO> petTypes = JsonConvert.DeserializeObject<List<PetTypeDTO>>(petTypesData);
                    ViewBag.PetTypes = petTypes;
                }
                else
                {
                    ModelState.AddModelError(string.Empty, "Lỗi khi lấy danh sách loại thú cưng.");
                }

                return View(petDTO);
            }
            else
            {
                string errorMessage = $"Failed to retrieve pet. Status code: {response.StatusCode}";
                return StatusCode((int)response.StatusCode, errorMessage);
            }
        }
        public async Task<IActionResult> CreatePet()
        {
            int? userId = HttpContext.Session.GetInt32("UserId");
            if (userId == null)
            {
                return RedirectToAction("Login", "Account");
            }

            ViewData["UserId"] = userId;
            HttpResponseMessage response = await _httpClient.GetAsync("pettype");
            if (response.IsSuccessStatusCode)
            {
                string data = await response.Content.ReadAsStringAsync();
                List<PetTypeDTO> petTypes = JsonConvert.DeserializeObject<List<PetTypeDTO>>(data);

                PetView petView = new()
                {
                    PetTypes = petTypes
                };

                return View(petView);
            }
            else
            {
                ModelState.AddModelError(string.Empty, "Lỗi khi lấy danh sách loại thú cưng.");
                return View();
            }
        }

        [HttpPost]
        public async Task<IActionResult> DeletePet(int id)
        {

MeoAndWoofClient/Views/Shared/AdminFunction.cshtml
@{
	ViewData["Title"] = "Admin Function";
	Layout = null;
}

<div class="left-side-bar">
	<div class="brand-logo">
		<a asp-action="Index" asp-controller="Home">
			<img src="/admin/vendors/images/deskapp-logo.svg" alt="" class="dark-logo">
			<img src="/admin/vendors/images/deskapp-logo-white.svg" alt="" class="light-logo">
		</a>
		<div class="close-sidebar" data-toggle="left-sidebar-close">
			<i class="ion-close-round"></i>
		</div>
	</div>
	<div class="menu-block customscroll">
		<div class="sidebar-menu">
			<ul id="accordion-menu">
				<li class="dropdown">
					<a href="javascript:;" class="dropdown-toggle">
						<span class="micon dw dw-house-1"></span><span class="mtext">Home</span>
					</a>
					<ul class="submenu">
						<li><a asp-controller="Home" asp-action="Index">Trang chủ của tôi</a></li>
						<li><a asp-controller="Admin" asp-action="Dashboard">Dashboard</a></li>
					</ul>
				</li>
				<li>
					<a asp-controller="Admin" asp-action="CuaHangThuCung" class="dropdown-toggle no-arrow">
						<span class="micon dw dw-library"></span><span class="mtext">Cửu hàng thú cưng</span>
					</a>
				</li>
				<li>
					<a asp-controller="Admin" asp-action="LuuTruThuCung" class="dropdown-toggle no-arrow">
						<span class="micon dw dw-library"></span><span class="mtext">Lưu trú thú cưng</span>
					</a>
				</li>
				<li>
					<a asp-controller="Admin" asp-action="Chart" class="dropdown-toggle no-arrow">
						<span class="micon dw dw-analytics-21"></span><span class="mtext">Biểu đồ</span>
					</a>
				</li>

				<li>
					<a asp-controller="Admin" asp-action="StoreProduct" class="dropdown-toggle no-arrow">
						<span class="micon dw dw-copy"></span><span class="mtext">Sản phẩm</span>
					</a>
				</li>
				<li>
					<a asp-controller="Admin" asp-action="Chat" class="dropdown-toggle no-arrow">
						<span class="micon dw dw-chat3"></span><span class="mtext">Chat</span>
					</a>
				</li>
			</ul>
		</div>
	</div>
</div>

MeoAndWoofClient/Views/Shared/AdminHeader.cshtml
@{
	ViewData["Title"] = "Admin Header";
	Layout = null;
}

<div class="header">
	<div class="header-left">
		<div class="menu-icon dw dw-menu"></div>
		<div class="search-toggle-icon dw dw-search2" data-toggle="header_search"></div>
		<div class="header-search">
			<form>
				<div class="form-group mb-0">
					<i class="dw dw-search2 search-icon"></i>
					<input type="text" class="form-control search-input" placeholder="Search Here">
					<div class="dropdown">
						<a class="dropdown-toggle no-arrow" href="#" role="button" data-toggle="dropdown">
							<i class="ion-arrow-down-c"></i>
						</a>
						<div class="dropdown-menu dropdown-menu-right">
							<div class="form-group row">
								<label class="col-sm-12 col-md-2 col-form-label">From</label>
								<div class="col-sm-12 col-md-10">
									<input class="form-control form-control-sm form-control-line" type="text">
								</div>
							</div>
							<div class="form-group row">
								<label class="col-sm-12 col-md-2 col-form-label">To</label>
								<div class="col-sm-12 col-md-10">
									<input class="form-control form-control-sm form-control-line" type="text">
								</div>
							</div>
							<div class="form-group row">
								<label class="col-sm-12 col-md-2 col-form-label">Subject</label>
								<div class="col-sm-12 col-md-10">
									<input class="form-control form-control-sm form-control-line" type="text">
								</div>
							</div>
							<div class="text-right">
								<button class="btn btn-primary">Search</button>
							</div>
						</div>
					</div>
				</div>
			</form>
		</div>
	</div>
	<div class="header-right">
		<div class="user-notification">
			<div class="dropdown">
				<a class="dropdown-toggle no-arrow" href="#" role="button" data-toggle="dropdown">
					<i class="icon-copy dw dw-notification"></i>
					<span class="badge notification-active"></span>
				</a>
				<div class="dropdown-menu dropdown-menu-right">
					<div class="notification-list mx-h-350 customscroll">
						<ul>
							<li>
								<a href="#">
									<img src="/admin/vendors/images/img.jpg" alt="">
									<h3>John Doe</h3>
									<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed...</p>
								</a>
							</li>
						</ul>
					</div>
				</div>
			</div>
		</div>
		<div class="user-info-dropdown">
			<div class="dropdown">
				<a class="dropdown-toggle" href="#" role="button" data-toggle="dropdown">
					<span class="user-icon">
						<img src="/admin/vendors/images/photo1.jpg" alt="">
					</span>
					<span class="user-name">Ross C. Lopez</span>
				</a>
				<div class="dropdown-menu dropdown-menu-right dropdown-menu-icon-list">
					<a class="dropdown-item" href="profile.html"><i class="dw dw-user1"></i> Profile</a>
					<a class="dropdown-item" href="profile.html"><i class="dw dw-settings2"></i> Setting</a>
					<a class="dropdown-item" href="faq.html"><i class="dw dw-help"></i> Help</a>
					<a class="dropdown-item" href="login.html"><i class="dw dw-logout"></i> Log Out</a>
				</div>
			</div>
		</div>
		<div class="github-link">
			<a href="https://github.com/dropways/deskapp" target="_blank"><img src="vendors/images/github.svg" alt=""></a>
		</div>
	</div>
</div>
<div class="right-sidebar">
	<div class="sidebar-title">
		<h3 class="weight-600 font-16 text-blue">
			Layout Settings
			<span class="btn-block font-weight-400 font-12">User Interface Settings</span>
		</h3>
		<div class="close-sidebar" data-toggle="right-sidebar-close">
			<i class="icon-copy ion-close-round"></i>
		</div>
	</div>
</div>

MeoAndWoofClient/Views/Shared/Header.cshtml
@inject Microsoft.AspNetCore.Mvc.Rendering.IHtmlHelper HtmlHelper
@inject Microsoft.AspNetCore.Http.IHttpContextAccessor HttpContextAccessor
@using Microsoft.AspNetCore.Authentication.Google
@{
    ViewData["Title"] = "Header";
    Layout = null;
    var currentController = HtmlHelper.ViewContext.RouteData.Values["controller"]?.ToString();
    var currentAction = HtmlHelper.ViewContext.RouteData.Values["action"]?.ToString();
    string NameUser = Context.Request.HttpContext.Session.GetString("NameUser");
    int? UserId = Context.Request.HttpContext.Session.GetInt32("UserId");
    string PhoneUser = Context.Request.HttpContext.Session.GetString("PhoneUser");
    string admin = Context.Request.HttpContext.Session.GetString("IsAdmin");
    string provider = Context.Request.HttpContext.Session.GetString("IsServiceProvider");
    string providerFace = Context.Request.HttpContext.Session.GetString("AuthProvider");
}
<!-- Topbar Start -->
<div class="container-fluid">
    <div class="row bg-secondary py-2 px-lg-5">
        <div class="col-lg-6 text-center text-lg-left mb-2 mb-lg-0">
            <div class="d-inline-flex align-items-center">
                <a class="text-white pr-3" href="">FAQs</a>
                <span class="text-white">|</span>
                <a class="text-white px-3" href="">Help</a>
                <span class="text-white">|</span>
                <a class="text-white pl-3" href="">Support</a>
            </div>
        </div>
        <div class="col-lg-6 text-center text-lg-right">
            <div class="d-inline-flex align-items-center">
                <a class="text-white px-3" href="">
                    <i class="fab fa-facebook-f"></i>
                </a>
                <a class="text-white px-3" href="">
                    <i class="fab fa-twitter"></i>
                </a>
                <a class="text-white px-3" href="">
                    <i class="fab fa-linkedin-in"></i>
                </a>
                <a class="text-white px-3" href="">
                    <i class="fab fa-instagram"></i>
                </a>
                <a class="text-white pl-3" href="">
                    <i class="fab fa-youtube"></i>
                </a>
            </div>
        </div>
    </div>
    <div class="row py-3 px-lg-5">
        <div class="col-lg-4">
            <a href="" class="navbar-brand d-none d-lg-block">
                <h1 class="m-0 display-5 text-capitalize">
                    <span class="text-primary text-custom">Meow</span> & <span class="text-custom-and">Woof</span>
                </h1>
            </a>
        </div>
        <div class="col-lg-8 text-center text-lg-right">
            <div class="d-inline-flex align-items-center">
                <div class="d-inline-flex flex-column text-center pr-3 border-right">
                    <h6>Opening Hours</h6>
                    <p class="m-0">7.00AM - 10.00PM</p>
                </div>
                <div class="d-inline-flex flex-column text-center px-3 border-right">
                    <h6>Email Us</h6>
                    <p class="m-0">anhkd2002@gmail.com</p>
                </div>
                <div class="d-inline-flex flex-column text-center pl-3">
                    <h6>Call Us</h6>
                    <p class="m-0">0374201805</p>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Topbar End -->
<!-- Navbar Start -->
<div class="container-fluid p-0">
    <nav class="navbar navbar-expand-lg bg-dark navbar-dark py-3 py-lg-0 px-lg-5">
        <a href="" class="navbar-brand d-block d-lg-none">
            <h1 class="m-0 display-5 text-capitalize font-italic text-white">
                <span class="text-primary">Safety</span>First
            </h1>
        </a>
        <button type="button"
                class="navbar-toggler"
                data-toggle="collapse"
                data-target="#navbarCollapse">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse justify-content-between px-3"
             id="navbarCollapse">
            <div class="navbar-nav mr-auto py-0">
                <a asp-controller="Home" asp-action="Index" class="nav-item nav-link @(currentAction == "Index" && currentController == "Home" ? "active" : "")">Trang Chủ</a>
                <a asp-controller="Home" asp-action="About" class="nav-item nav-link @(currentAction == "About" && currentController == "Home" ? "active" : "")">Giới Thiệu</a>
                <a asp-controller="Home" asp-action="Services" class="nav-item nav-link @(currentAction == "Services" && currentController == "Home" ? "active" : "")">Dịch Vụ</a>
                <a asp-controller="Home" asp-action="Price" class="nav-item nav-link @(currentAction == "Price" && currentController == "Home" ? "active" : "")">Giá Cả</a>
                <a asp-controller="Home" asp-action="Booking" class="nav-item nav-link @(currentAction == "Booking" && currentController == "Home" ? "active" : "")">Đặt Chỗ</a>
                <a asp-controller="Home" asp-action="Blog" class="nav-item nav-link @(currentAction == "Blog" && currentController == "Home" ? "active" : "")">Bài Viết</a>
                <a asp-controller="Home" asp-action="Contact" class="nav-item nav-link @(currentAction == "Contact" && currentController == "Home" ? "active" : "")">Liên Hệ</a>
            </div>
            @if (NameUser == null)
            {
                <a asp-controller="Authen" asp-action="Login"
                   class="btn btn-lg btn-primary px-3 d-none d-lg-block">Đăng Nhập</a>
                <a asp-controller="Authen" asp-action="Register"
                   class="btn btn-lg btn-primary px-3 d-none d-lg-block ml-3">Đăng Ký</a>
            }
            else
            {
                <div style="color: #efb1c9" class="btn-group dropdown dropleft">
                    <i style="font-size: 30px"
                       class="fa-solid fa-user"
                       data-toggle="dropdown"></i>
                    <div class="dropdown-menu">
                        <button class="dropdown-item" type="button">
                            <a href="#">
                                <i class="fa-solid fa-circle-info"></i> &nbsp;&nbsp; @NameUser
                            </a>
                        </button>
                        <hr class="mt-2 mb-2" />
                        <button class="dropdown-item" type="button">
                            <a asp-controller="User" asp-action="Information" asp-route-id="@UserId">
                                <i class="fa-solid fa-circle-info"></i> &nbsp;&nbsp; Thông tin
                            </a>
                        </button>
                        @if (HttpContextAccessor.HttpContext.Session.GetString("AuthProvider") != GoogleDefaults.AuthenticationScheme || Context.Request.HttpContext.Session.GetString("AuthProvider") == "FaceBook")
                        {
                            <button class="dropdown-item" type="button">
                                <a asp-controller="User" asp-action="ChangePass" asp-route-id="@UserId">
                                    <i class="fa-solid fa-lock"></i>&nbsp;&nbsp;  Đổi mật khẩu
                                </a>
                            </button>
                        }
                        <button class="dropdown-item" type="button">
                            <a asp-controller="User" asp-action="HistoryBooking" asp-route-id="@UserId">
                                <i class="fa-solid fa-clock-rotate-left"></i>
                                &nbsp;&nbsp;Lịch sử đặt hẹn
                            </a>
                        </button>
                        <button class="dropdown-item" type="button">
                            <a asp-controller="User" asp-action="HistoryStore" asp-route-id="@UserId">
                                <i class="fa-solid fa-clock-rotate-left"></i>
                                &nbsp;&nbsp;Lịch sử mua hàng
                            </a>
                        </button>
                        <button class="dropdown-item" type="button">
                            <a asp-controller="Authen" asp-action="Logout">
                                <i class="fa-solid fa-right-from-bracket"></i>
                                &nbsp;&nbsp;Đăng xuất
                            </a>
                        </button>
                    </div>
                </div>
            }
        </div>
    </nav>
</div>
<!-- Navbar End -->

MeoAndWoofClient/Views/Shared/SupplierFunction.cshtml
@{
	ViewData["Title"] = "Admin Function";
	Layout = null;
}

<div class="left-side-bar">
	<div class="brand-logo">
		<a asp-action="Index" asp-controller="Home">
			<img src="/admin/vendors/images/deskapp-logo.svg" alt="" class="dark-logo">
			<img src="/admin/vendors/images/deskapp-logo-white.svg" alt="" class="light-logo">
		</a>
		<div class="close-sidebar" data-toggle="left-sidebar-close">
			<i class="ion-close-round"></i>
		</div>
	</div>
	<div class="menu-block customscroll">
		<div class="sidebar-menu">
			<ul id="accordion-menu">
				<li class="dropdown">
					<a href="javascript:;" class="dropdown-toggle">
						<span class="micon dw dw-house-1"></span><span class="mtext">Home</span>
					</a>
					<ul class="submenu">
						<li><a asp-controller="Home" asp-action="Index">Trang chủ của tôi</a></li>
						<li><a asp-controller="Supplier" asp-action="Dashboard">Dashboard</a></li>
					</ul>
				</li>
				<li>
					<a asp-controller="Supplier" asp-action="CuaHangThuCung" class="dropdown-toggle no-arrow">
						<span class="micon dw dw-library"></span><span class="mtext">Cửu hàng thú cưng</span>
					</a>
				</li>
				<li>
					<a asp-controller="Supplier" asp-action="LuuTruThuCung" class="dropdown-toggle no-arrow">
						<span class="micon dw dw-library"></span><span class="mtext">Lưu trú thú cưng</span>
					</a>
				</li>
				<li>
					<a asp-controller="Supplier" asp-action="ListOrder" class="dropdown-toggle no-arrow">
						<span class="micon dw dw-chat3"></span><span class="mtext">Đơn hàng </span>
					</a>
				</li>
				<li>
					<a asp-controller="Supplier" asp-action="ListBooking" class="dropdown-toggle no-arrow">
						<span class="micon dw dw-chat3"></span><span class="mtext">Đơn đặt hẹn</span>
					</a>
				</li>
				<li>
					<a asp-controller="Supplier" asp-action="Chart" class="dropdown-toggle no-arrow">
						<span class="micon dw dw-analytics-21"></span><span class="mtext">Biểu đồ</span>
					</a>
				</li>
				<li>
					<a asp-controller="Supplier" asp-action="Chat" class="dropdown-toggle no-arrow">
						<span class="micon dw dw-chat3"></span><span class="mtext">Chat</span>
					</a>
				</li>
			</ul>
		</div>
	</div>
</div>